server:
  port: 8080

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
      routes:
        - id: microservice-user
          uri: lb://microservice-user
          predicates:
            - Path=/user/**
          filters:
<<<<<<< HEAD
            - AuthFilter
=======
            - RemoveRequestHeader=Cookie
>>>>>>> 7b88a6cac44b5414da848f55bf439471c467697e
        - id: microservice-car
          uri: lb://microservice-car
          predicates:
            - Path=/car/**
        - id: microservice-motorcycle
          uri: lb://microservice-motorcycle
          predicates:
            - Path=/motorcycle/**
<<<<<<< HEAD
        - id: microservice-auth
          uri: lb://microservice-auth
          predicates:
            - Path=/auth/**
=======
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: http://localhost:8180/realms/practica-realm/protocol/openid-connect/auth
            userinfo-uri: http://localhost:8180/realms/practica-realm/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
            token-uri: http://localhost:8180/realms/practica-realm/protocol/openid-connect/token
        registration:
          practica-cliente:
            provider: keycloak
            client-id: practica-cliente
            client-secret: Qz7eXBRzjY6kDbAFkTglpVWBYopPh0Ej
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/practica-cliente"
>>>>>>> 7b88a6cac44b5414da848f55bf439471c467697e
          

