spring:
  application:
    name: microservice-auth
  config:
    import: "optional:configserver:http://localhost:8081"
  datasource:
    url: jdbc:mysql://localhost:3306/microserviceauth
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  secret: E54791C31B99A58F25677B21FAECD57AB89CDEF1234567890ABCDEF12345678

admin-paths:
    paths:
      -
        uri: "/user"
        method: "POST"

      -
        uri: "/user/saveCar/{1}[1-9]+[0-9]*"
        method: "POST"

      -
        uri: "/user/saveMotorcycle/{1}[1-9]+[0-9]*"
        method: "POST"